# Generated by Django 3.1.1 on 2020-12-19 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201209_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disrepair',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FailureName', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='abonent',
            name='Counter',
        ),
    ]
