# Generated by Django 3.1.1 on 2021-01-06 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201219_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbonMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Counter', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Executor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FIO', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ModeName', models.CharField(max_length=120)),
                ('Norma', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='RecepPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RecepName', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServiceName', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='abonent',
            name='HouseNo',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='abonent',
            name='SizeFlat',
            field=models.FloatField(default=1.5),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AccountCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonent')),
                ('ExecutorCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.executor')),
                ('FailureCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.disrepair')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Price', models.FloatField()),
                ('ModeCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mode')),
            ],
        ),
        migrations.CreateModel(
            name='PaySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CountMD', models.FloatField()),
                ('PayDate', models.DateField()),
                ('PayMonth', models.SmallIntegerField()),
                ('PayYear', models.SmallIntegerField()),
                ('PaySum', models.FloatField()),
                ('AbonentMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonmode')),
                ('AccountCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonent')),
                ('ReceptionPoint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.receppoint')),
            ],
        ),
        migrations.CreateModel(
            name='NachislSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NachislMonth', models.SmallIntegerField()),
                ('NachislYear', models.SmallIntegerField()),
                ('NachislDate', models.DateField()),
                ('CountMD', models.FloatField()),
                ('Nachislsum', models.FloatField()),
                ('AbonentMode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonmode')),
                ('AccountCD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonent')),
            ],
        ),
        migrations.AddField(
            model_name='mode',
            name='ServiceCD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.services'),
        ),
        migrations.AddField(
            model_name='abonmode',
            name='AccountCD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.abonent'),
        ),
        migrations.AddField(
            model_name='abonmode',
            name='ModeCD',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mode'),
        ),
    ]
